# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_destination.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15get_destination.proto\"/\n\x0f\x43urrentLocation\x12\r\n\x05pos_x\x18\x01 \x01(\x05\x12\r\n\x05pos_y\x18\x02 \x01(\x05\"+\n\x0b\x44\x65stination\x12\r\n\x05pos_x\x18\x01 \x01(\x05\x12\r\n\x05pos_y\x18\x02 \x01(\x05\x32\x44\n\x0eGetDestination\x12\x32\n\x0eGetDestination\x12\x10.CurrentLocation\x1a\x0c.Destination\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_destination_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CURRENTLOCATION']._serialized_start=25
  _globals['_CURRENTLOCATION']._serialized_end=72
  _globals['_DESTINATION']._serialized_start=74
  _globals['_DESTINATION']._serialized_end=117
  _globals['_GETDESTINATION']._serialized_start=119
  _globals['_GETDESTINATION']._serialized_end=187
# @@protoc_insertion_point(module_scope)
