# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matching_pair.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13matching_pair.proto\"V\n\x0fMatchingRequest\x12\x17\n\x04type\x18\x01 \x01(\x0e\x32\t.PairType\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\"\x1f\n\x0cReturnStatus\x12\x0f\n\x07message\x18\x01 \x01(\t*/\n\x08PairType\x12\n\n\x06\x44RIVER\x10\x00\x12\x0c\n\x08\x43USTOMER\x10\x01\x12\t\n\x05RESET\x10\x02\x32;\n\x0fMatchingService\x12(\n\x05Match\x12\x10.MatchingRequest\x1a\r.ReturnStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matching_pair_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PAIRTYPE']._serialized_start=144
  _globals['_PAIRTYPE']._serialized_end=191
  _globals['_MATCHINGREQUEST']._serialized_start=23
  _globals['_MATCHINGREQUEST']._serialized_end=109
  _globals['_RETURNSTATUS']._serialized_start=111
  _globals['_RETURNSTATUS']._serialized_end=142
  _globals['_MATCHINGSERVICE']._serialized_start=193
  _globals['_MATCHINGSERVICE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
